# Generated by Django 3.2.5 on 2021-07-24 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_kor', models.CharField(max_length=100)),
                ('title_eng', models.CharField(max_length=100)),
                ('poster_url', models.TextField()),
                ('rating_aud', models.CharField(max_length=50)),
                ('rating_cri', models.CharField(max_length=50)),
                ('rating_net', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('showtimes', models.CharField(max_length=50)),
                ('release_date', models.CharField(max_length=50)),
                ('rate', models.CharField(max_length=50)),
                ('summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('image_url', models.TextField()),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='movie.movie')),
            ],
        ),
    ]
